### ISSUE TITLE
duplicated data

### ISSUE THREAD

**Issue by fedhere** [fedhere/SESNspectraPCA#4]
is the data in, e.g. PCvsTemplates duplicated data that exists in another SNYU repo? if so it sould be removed and the readme and codes shuld point to the data already on github

"/PCvsTemplates contains mean spectra for the phase 15 days presented in Liu et al. 2016. These are used to compare the mean spectra with the eigenspectra calculated by our PCA analysis."

**Comment by marxwillia** [comment]
Readme's give detailed instructions on how to compile the SNID library and download the mean spectra. There are no more duplicated data products in this repo.
