### ISSUE TITLE
SNePCAplots

### ISSUE THREAD

**Issue by fedhere** [fedhere/SESNspectraPCA#5]
the static figures need not be saved on github. only added value figures need to be accessible here. **what you need though is the code that generated the figures**. If you also share your latex and latex makefile taht generates the PDF then save the figures as needed, but that all should be in a directory caller, e.g., /paper

**Comment by marxwillia** [comment]
Only supplemental plots are kept.  A script has been written to generate each of the figures from the paper and stored in /code/PlotScripts.
